# Site settings
title: AI World !!
description: Modern-Blog A NLP To Make Things Esy
keywords: Modern, Blogging, Fun
author: Ajith
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ajithaiworld.github.io/ai-world/" # the base hostname & protocol for your site
